
services:
  app:
    build: .
    image: rag
    ports:
      - "8000:8000"
    env_file:
      - .env
  streamlit:
    image: rag  # Use the same image to ensure dependencies are included
    command: streamlit run streamlit_app.py
    ports:
      - "8501:8501"
    depends_on:
      - app
    env_file:
      - .env
