version: '3.9'

services:
  app:
    build: .
    image: rag
    ports:
      - "8000:8000"
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  streamlit:
    image: rag  
    command: streamlit run streamlit_app.py
    ports:
      - "8501:8501"
    depends_on:
      app:
        condition: service_healthy
    env_file:
      - .env
